export const LOGIN_REQUEST = "user:LOGIN_REQUEST";
export const LOGIN_SUCCESS = "user:LOGIN_SUCCESS";
export const LOGIN_FAILURE = "user:LOGIN_FAILURE";

export const LOGOUT_REQUEST = "user:LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "user:LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "user:LOGOUT_FAILURE";

export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE
};
