export const LOAD_FRIENDS_REQUEST = 'friends:LOAD_FRIENDS_REQUEST';
export const LOAD_FRIENDS_SUCCESS = 'friends:LOAD_FRIENDS_SUCCESS';
export const LOAD_FRIENDS_FAILURE = 'friends:LOAD_FRIENDS_FAILURE';

export default {
  LOAD_FRIENDS_REQUEST,
  LOAD_FRIENDS_SUCCESS,
  LOAD_FRIENDS_FAILURE,
};
