export const LOAD_DASHBOARD_REQUEST = "dashboard:LOAD_DASHBOARD_REQUEST";
export const LOAD_DASHBOARD_SUCCESS = "dashboard:LOAD_DASHBOARD_SUCCESS";
export const LOAD_DASHBOARD_FAILURE = "dashboard:LOAD_DASHBOARD_FAILURE";

export default {
  LOAD_DASHBOARD_REQUEST,
  LOAD_DASHBOARD_SUCCESS,
  LOAD_DASHBOARD_FAILURE
};
